language: go

arch:
  - amd64
  - ppc64le

go:
  - 1.12.x

go_import_path: github.com/konveyor/openshift-velero-plugin

sudo: required

services:
  - docker

before_script:
  - sudo apt-get -qq update

script:
  - make ci
